/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
   
    "Auth": {
        "region": "us-west-2",
        "userPoolId": "us-west-2_M7L0hmn2y",
        "userPoolWebClientId": "7siqiajm3r6pi6m8mdu24pudnf"
    }
};


export default awsExports;